#include "callback_container.h"

// for p1 type--------------------------------------------------------
SOURCE_CALLBACK_CONTAINER_MACRO(void, p1);
SOURCE_CALLBACK_CONTAINER_MACRO(u8,   p1);
SOURCE_CALLBACK_CONTAINER_MACRO(u16,  p1);
SOURCE_CALLBACK_CONTAINER_MACRO(u24,  p1);
SOURCE_CALLBACK_CONTAINER_MACRO(u32,  p1);
SOURCE_CALLBACK_CONTAINER_MACRO(u64,  p1);

SOURCE_CALLBACK_CONTAINER_MACRO(c8,   p1);
SOURCE_CALLBACK_CONTAINER_MACRO(i8,   p1);
SOURCE_CALLBACK_CONTAINER_MACRO(i16,  p1);
SOURCE_CALLBACK_CONTAINER_MACRO(i24,  p1);
SOURCE_CALLBACK_CONTAINER_MACRO(i32,  p1);
SOURCE_CALLBACK_CONTAINER_MACRO(i64,  p1);

SOURCE_CALLBACK_CONTAINER_MACRO(f32,  p1);
SOURCE_CALLBACK_CONTAINER_MACRO(f64,  p1);
SOURCE_CALLBACK_CONTAINER_MACRO(f128, p1);

SOURCE_CALLBACK_CONTAINER_MACRO(b,    p1);
SOURCE_CALLBACK_CONTAINER_MACRO(reg,  p1);
SOURCE_CALLBACK_CONTAINER_MACRO(sreg, p1);

// for p2 type---------------------------------------------------------
SOURCE_CALLBACK_CONTAINER_MACRO(void, p2);
SOURCE_CALLBACK_CONTAINER_MACRO(u8,   p2);
SOURCE_CALLBACK_CONTAINER_MACRO(u16,  p2);
SOURCE_CALLBACK_CONTAINER_MACRO(u24,  p2);
SOURCE_CALLBACK_CONTAINER_MACRO(u32,  p2);
SOURCE_CALLBACK_CONTAINER_MACRO(u64,  p2);

SOURCE_CALLBACK_CONTAINER_MACRO(c8,   p2);
SOURCE_CALLBACK_CONTAINER_MACRO(i8,   p2);
SOURCE_CALLBACK_CONTAINER_MACRO(i16,  p2);
SOURCE_CALLBACK_CONTAINER_MACRO(i24,  p2);
SOURCE_CALLBACK_CONTAINER_MACRO(i32,  p2);
SOURCE_CALLBACK_CONTAINER_MACRO(i64,  p2);

SOURCE_CALLBACK_CONTAINER_MACRO(f32,  p2);
SOURCE_CALLBACK_CONTAINER_MACRO(f64,  p2);
SOURCE_CALLBACK_CONTAINER_MACRO(f128, p2);

SOURCE_CALLBACK_CONTAINER_MACRO(b,    p2);
SOURCE_CALLBACK_CONTAINER_MACRO(reg,  p2);
SOURCE_CALLBACK_CONTAINER_MACRO(sreg, p2);


#undef SOURCE_CALLBACK_CONTAINER_MACRO
